embedding_type: ["esm3", "proteinmpnn", "prot_domain_classifier", "foldseek"]
reference_structures: "cath"
sampled_structures: "tests/test_data"
output_dir: "out_dir"
embed_reference: False
embed_samples: True
